#!/bin/sh
set -eu
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}
export PATH
script_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd -P)
. "$script_dir/_toolchain"
install_tool_main desktop-file-utils "$@"
